### ISSUE TITLE
form の text でエンターキーを押すと送信エラーになる

### ISSUE THREAD

**Issue by shintarou-hiraiwa-d** [shintarou-hiraiwa-d/node-form-practice#2]
### 問題内容
送信ボタンをクリックする代わりに、エンターキーを押下すると、hello-form.html?name=入力内容 にアクセスしてしまい、404になる。

### 実行環境
- Windows 10 64bit
- Google Chrome 71
- Node.js v10.13.0

### 再現手順
1. server.js を起動する。
2. hello-form.html をブラウザで開く。
3. 入力ボックスをフォーカスする。
4. フォーカスされた状態で、エンターキーを押す(何か入力しても、しなくても良い。)。

### 修正すべき内容
- エンターキーを押した時も、クリックした時と同様に、フォーム下部に入力内容が表示されるようにする。
- 原因・修正方法は調査中。

**Comment by shintarou-hiraiwa-d** [comment]
書き忘れてましたが、
> エンターキーで送信時にエラーが発生してしまう不具合の修正 #3

は、ブランチの切り方が不適切だったため、削除して、作り直しました。

**Comment by yoshiyuki-miyagi-d** [comment]
> エンターキーで送信時にエラー

"form の text でエンターキーを押すと送信エラーになる"

というように内容に具体的なタイトルをつける練習をしましょう。
